import { StyleSheet } from 'react-native';
import { Colors, Fonts } from '..';

const OrderScreenLtrStyle = StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    backgroundColor: Colors.white,
  },
  title: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 0,
    marginRight: 'auto',
    paddingTop: 10,
    paddingBottom: 10,
  },
  title_text: {
    fontSize: Fonts.regular,
    fontWeight: '600',
    color: Colors.black,
  },
  title_text_gray: {
    fontSize: Fonts.medium,
    color: Colors.greyIrina,
  },
  order_details_container: {
    display: 'flex',
    flexDirection: 'column',
    // flex: 1,
    paddingLeft: 15,
    paddingRight: 15,
  },
  order_details_list: {
    // backgroundColor: Colors.lightGreyIrina,
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
  },
  order_detail: {
    paddingTop: 5,
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignContent: 'center',
  },
  order_detail_title: {
    fontWeight: 'bold',
    fontSize: Fonts.small,
    color: Colors.greyIrina,
  },
  order_detail_value: {
    fontSize: Fonts.h5,
    color: Colors.black,
    fontWeight: 'bold',
    paddingLeft: 10,
  },
  offers_received: {
    fontSize: Fonts.h6,
    fontWeight: 'bold',
    color: Colors.greyIrina,
    padding: 10,
    marginLeft: 15,
    marginRight: 15,
    borderBottomWidth: 2,
    borderBottomColor: Colors.lightGreyIrina,
    backgroundColor: Colors.white,
  },
  order_details: {
    marginBottom: 20,
    paddingBottom: 20,
    borderBottomColor: Colors.greyIrina,
    borderBottomWidth: 1,
    paddingHorizontal: 5,
  },
  order_address: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 7,
  },
  order_address_title: {},
  order_address_value: {
    color: Colors.black,
    fontSize: Fonts.medium,
    paddingLeft: 5,
  },
  order_additional_details: {},
  list: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
  },
  list_item: {
    marginHorizontal: 15,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  list_item_title: {
    paddingLeft: 15,
    paddingRight: 15,
    fontSize: Fonts.medium,
    color: Colors.black,
    fontWeight: 'bold',
    height: Fonts.medium * 3,
    textAlignVertical: 'center',
    width: '70%',
  },
  list_item_details: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignContent: 'center',
  },
  list_item_top: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 5,
    color: Colors.white,
  },
  list_item_time: {
    paddingTop: 7,
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignContent: 'center',
  },
  list_item_time_title: {
    fontSize: Fonts.medium,
    fontWeight: 'bold',
    color: Colors.white,
  },
  list_item_time_value: {
    paddingTop: 2,
    fontSize: Fonts.small,
    color: Colors.white,
  },
  list_item_bottom: {
    backgroundColor: Colors.lightGreyIrina,
    width: '100%',
    padding: 10,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignContent: 'center',
  },
  list_item_detail: {
    paddingLeft: 15,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  list_item_detail_bottom: {
    paddingLeft: 15,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  list_item_detail_title: {
    fontSize: Fonts.medium,
    fontWeight: 'bold',
    color: Colors.greyIrina,
    paddingLeft: 10,
  },
  list_item_detail_price_container: {
    display: 'flex',
    flexDirection: 'row',
    paddingLeft: 10,
    alignItems: 'center',
  },
  list_item_detail_price: {
    fontSize: Fonts.regular,
    color: Colors.black,
    fontWeight: 'bold',
  },
  list_item_detail_price_currency: {
    fontSize: Fonts.regular,
    color: Colors.black,
    paddingLeft: 5,
  },
  list_item_detail_price_vat: {
    paddingLeft: 7,
    fontSize: Fonts.medium,
    color: Colors.greyIrina,
  },
  list_item_detail_advance: {
    paddingTop: 2,
    fontSize: Fonts.medium,
    color: Colors.black,
  },
});

export default OrderScreenLtrStyle;
