import { StyleSheet } from 'react-native';
import { Colors, Fonts, Metrics } from '../../themes';

const appointmentScreenLtrStyle = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  title: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 'auto',
    marginRight: 'auto',
    paddingTop: 10,
    paddingBottom: 10,
  },
  title_text: {
    fontSize: Fonts.medium,
    color: Colors.black,
    fontWeight: 'bold',
  },
  inputs: {
    paddingVertical: 15,
    paddingLeft: 15,
  },
  inputItem: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputItemLeft: {
    paddingVertical: 15,
    minWidth: 30,
  },
  inputItemRight: {
    flex: 1,
    marginLeft: 15,
    paddingRight: 15,
    paddingVertical: 15,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: Colors.darkGreyIrina,
  },
  inputItemRightNoSeparator: {
    flex: 1,
    marginLeft: 15,
    paddingRight: 15,
    marginBottom: 10,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inputIcon: {
    marginLeft: 5,
  },
  inputLabels: {
    display: 'flex',
    flexDirection: 'column',
    paddingLeft: 15,
    width: '80%',
  },
  inputTitle: {
    fontSize: Fonts.medium,
    color: Colors.black,
  },
  inputValue: {
    fontSize: Fonts.h5,
    color: Colors.black,
  },
  delivery_address: {
    marginTop: 10,
  },
  delivery_address_title: {
    fontSize: Fonts.medium,
    color: Colors.black,
    fontWeight: 'bold',
  },
  delivery_address_value: {
    fontWeight: 'bold',
    paddingTop: 5,
    color: Colors.black,
    fontSize: Fonts.medium,
  },
  delivery_date_title: {
    fontWeight: 'bold',
    fontSize: Fonts.medium,
    color: Colors.black,
    marginTop: 0,
  },
  delivery_time_container: {
    marginTop: 50,
    height: 50,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    borderRadius: 10,
  },
  date_picker: {
    width: 150,
    height: 35,
    color: Colors.black,
    backgroundColor: Colors.lightGreyIrina,
    marginBottom: 3,
  },
  delivery_time_details: {
    width: 150,
    height: 35,
    borderWidth: 1,
    borderColor: Colors.black,
    backgroundColor: Colors.lightGreyIrina,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  delivery_time_value: {
    fontSize: Fonts.medium,
    color: Colors.black,
  },
  quantity_container: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
    paddingTop: 0,
    paddingBottom: 0,
    marginTop: 10,
  },
  quantity_unit: {
    marginLeft: 5,
    paddingLeft: 0,
    fontSize: Fonts.medium,
    color: Colors.black,
  },
  price_unit: {
    marginTop: 10,
    marginLeft: 0,
    paddingLeft: 0,
    fontSize: Fonts.regular,
  },
  chooseSuppliersButton_disabled: {
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: 40,
    backgroundColor: 'transparent',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors.black,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  chooseSuppliersButton: {
    backgroundColor: Colors.green,
    borderRadius: 10,
    paddingHorizontal: 25,
    padding: Fonts.medium,
    marginHorizontal: 15,
    marginTop: 15,
  },
  chooseSuppliersButtonText_disabled: {
    paddingVertical: 17,
    paddingHorizontal: 75,
    color: Colors.black,
    fontSize: Fonts.medium,
    fontWeight: 'bold',
  },
  chooseSuppliersButtonText: {
    paddingVertical: 17,
    paddingHorizontal: 75,
    color: Colors.white,
    fontSize: Fonts.medium,
    fontWeight: 'bold',
  },
  popupContainer: {
    zIndex: 15,
    position: 'absolute',
    width: '100%',
    height: '100%',
    top: 0,
    left: 0,
    backgroundColor: 'rgba(0,0,0,0.16)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  popup: {
    padding: 15,
    width: '80%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: 20,
  },
  popupHeader: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    // marginBottom: 10,
  },
  popupHeaderText: {
    fontSize: Fonts.regular,
    color: Colors.black,
  },
  saveButton: {
    marginTop: 30,
    marginBottom: 5,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '60%',
    fontSize: Fonts.h5,
    backgroundColor: Colors.green,
    fontWeight: 'bold',
    paddingVertical: 10,
    borderRadius: 10,
  },
  saveButtonText: {
    textAlign: 'center',
    shadowColor: '#000',
    color: Colors.white,
    fontSize: Fonts.regular,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.5,
    shadowRadius: 6.65,
    elevation: 8,
  },
  concreteSelectorHeader: {
    paddingVertical: 15,
    paddingHorizontal: 25,
    marginTop: 10,
    flexDirection: 'row',
    display: 'flex',
    justifyContent: 'space-between',
  },
  concreteSelected: {
    backgroundColor: Colors.black,
  },
  concreteUnselected: {
    backgroundColor: 'transparent',
    borderBottomColor: Colors.lightGrey,
    borderBottomWidth: 1,
  },
  concreteOptionText: {
    fontSize: Fonts.medium,
    paddingBottom: 20,
    marginBottom: 20,
    paddingLeft: 10,
    color: Colors.black,
  },
  spacer: {
    width: 30,
    textAlign: 'center',
    fontSize: Fonts.regular,
  },
  supplierOptionsContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    padding: 5,
  },
  supplierOptionsView: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    width: '90%',
    borderBottomWidth: 1,
    borderBottomColor: Colors.lightGreyIrina,
    padding: 5,
    marginBottom: 10,
  },
  supplierOptionsViewNoSeparator: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    width: '90%',
    padding: 5,
    marginBottom: 10,
  },
});

export const pickerStyle = {
  inputAndroid: {
    fontSize: Fonts.regular,
    color: Colors.black,
    // backgroundColor: 'red'
    // fontFamily: 'SFUIDisplayMedium',
  },
  inputIOS: {
    fontSize: Fonts.regular,
    color: Colors.black,
    // fontFamily: 'SFUIDisplay-Medium',
  },
  placeholder: {
    fontSize: Fonts.regular,
    color: Colors.greyIrina,
    // fontFamily: Platform.OS === 'android' ? 'SFUIDisplayMedium' : 'SFUIDisplay-Medium',
  },
};

export default appointmentScreenLtrStyle;
